opcalendar/urls.py
from django.urls import path

from . import views

app_name = "opcalendar"
urlpatterns = [
    path("index", views.index, name="index"),
    path("", views.CalendarView.as_view(), name="calendar"),
    path("event/new/", views.create_event, name="event_new"),
    path("add_ingame_calendar/", views.add_ingame_calendar, name="add_ingame_calendar"),
    path("event/edit/<int:event_id>/", views.EventEdit, name="event_edit"),
    path("event/<int:event_id>/details/", views.event_details, name="event-detail"),
    path(
        "ingame/event/<int:event_id>/details/",
        views.ingame_event_details,
        name="ingame-event-detail",
    ),
    path(
        "add_eventmember/<int:event_id>",
        views.EventMemberSignup,
        name="event_member_signup",
    ),
    path("event/<int:event_id>/remove", views.EventDeleteView, name="remove_event"),
    path(
        "remove_eventmember/<int:event_id>",
        views.EventMemberRemove,
        name="event_member_remove",
    ),
    path("feed.ics", views.EventFeed()),
    path(
        "event/<int:event_id>/details/feed.ics",
        views.EventIcalView(),
        name="event-ical-view",
    ),
    path("event/new/ajax/get_category/", views.get_category, name="get_category"),
]

opcalendar/models.py
import json
from datetime import datetime, timedelta
from typing import Tuple

import requests
from allianceauth.authentication.models import CharacterOwnership, State
from allianceauth.eveonline.models import EveCharacter, EveCorporationInfo
from allianceauth.services.hooks import get_extension_logger
from django.contrib.auth.models import Group, User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.html import strip_tags
from django.utils.translation import gettext_lazy as _
from esi.errors import TokenExpiredError, TokenInvalidError
from esi.models import Token

from .decorators import fetch_token_for_owner
from .providers import esi

logger = get_extension_logger(__name__)


class General(models.Model):
    """Meta model for app permissions"""

    class Meta:
        managed = False
        default_permissions = ()
        permissions = (
            (
                "basic_access",
                "Can access this app and see operations based on visibility rules",
            ),
            ("create_event", "Can create and edit events"),
            ("see_signups", "Can see all signups for event"),
            ("manage_event", "Can delete and manage other signups"),
            (
                "add_ingame_calendar_owner",
                "Can add ingame calendar feeds for their corporation",
            ),
        )


class WebHook(models.Model):
    """Discord Webhook for pings"""

    name = models.CharField(
        max_length=150,
        help_text=_("Name for this webhook"),
    )
    webhook_url = models.CharField(
        max_length=500,
        help_text=_("Webhook URL"),
    )
    enabled = models.BooleanField(default=True, help_text=_("Is the webhook enabled?"))

    def send_embed(self, embed):
        custom_headers = {"Content-Type": "application/json"}
        data = '{"embeds": [%s]}' % json.dumps(embed)
        r = requests.post(self.webhook_url, headers=custom_headers, data=data)
        r.raise_for_status()

    class Meta:
        verbose_name = "Webhook"
        verbose_name_plural = "Webhooks"

    def __str__(self):
        return "{}".format(self.name)


class EventVisibility(models.Model):
    name = models.CharField(
        max_length=150, null=False, help_text="Name for the visibility filter"
    )
    restricted_to_group = models.ManyToManyField(
        Group,
        blank=True,
        related_name="eventvisibility_require_groups",
        help_text=_(
            "The group(s) that will be able to see this event visibility type ..."
        ),
    )
    restricted_to_state = models.ManyToManyField(
        State,
        blank=True,
        related_name="eventvisibility_require_states",
        help_text=_(
            "The state(s) that will be able to see this event visibility type ..."
        ),
    )
    webhook = models.ForeignKey(
        WebHook,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        help_text=_("Webhook to send over notifications about these fleet types"),
    )
    ignore_past_fleets = models.BooleanField(
        default=True,
        help_text=_("Should we ignore fleet signals that are in the past"),
    )
    color = models.CharField(
        max_length=7,
        default="",
        blank=True,
        help_text=_("Color to be displayed on calendar"),
    )
    include_in_feed = models.BooleanField(
        default=False,
        help_text=("Whether these events should be included in the ical feed."),
    )
    is_visible = models.BooleanField(
        default=True,
        help_text=(
            "Whether this visibility filter should be displayed on the event form. Disable for internal visibilities such as the NPSI import fleet visibilities."
        ),
    )
    is_default = models.BooleanField(
        default=False,
        help_text=(
            "Whether this visibility filter is used as the default value on the event form"
        ),
    )
    is_active = models.BooleanField(
        default=True,
        help_text=("Whether this visibility filter is active"),
    )

    def __str__(self) -> str:
        return str(self.name)

    class Meta:
        verbose_name = "Event Visibility Filter"
        verbose_name_plural = "Event Visibilities Filters"

    def save(self, *args, **kwargs):
        if self.is_default:
            # select all other is_default items
            qs = type(self).objects.filter(is_default=True)
            # except self (if self already exists)
            if self.pk:
                qs = qs.exclude(pk=self.pk)
            # and deactive them
            qs.update(is_default=False)

        super(EventVisibility, self).save(*args, **kwargs)

    @property
    def get_visibility_class(self):
        return f"{self.name.replace(' ', '-').lower()}"


class EventHost(models.Model):
    """Fleet Timer Create/Delete pings"""

    community = models.CharField(
        max_length=150, null=False, help_text="Name of the community"
    )
    logo_url = models.CharField(
        max_length=256, blank=True, help_text="Absolute URL for the community logo"
    )
    ingame_channel = models.CharField(
        max_length=150, blank=True, help_text="Ingame channel name"
    )
    ingame_mailing_list = models.CharField(
        max_length=150, blank=True, help_text="Ingame mailing list name"
    )
    fleet_comms = models.CharField(
        max_length=150,
        blank=True,
        help_text="Link or description for primary comms such as discord link",
    )
    fleet_doctrines = models.CharField(
        max_length=150, blank=True, help_text="Link or description to the doctrines"
    )
    website = models.CharField(max_length=150, blank=True, help_text="Website link URL")
    discord = models.CharField(max_length=150, blank=True, help_text="Discord link URL")
    twitch = models.CharField(max_length=150, blank=True, help_text="Twitch link URL")
    twitter = models.CharField(max_length=150, blank=True, help_text="Twitter link URL")
    youtube = models.CharField(max_length=150, blank=True, help_text="Youtube link URL")
    facebook = models.CharField(
        max_length=150, blank=True, help_text="Facebook link URL"
    )
    details = models.CharField(
        max_length=150, blank=True, help_text="Short description about the host."
    )
    is_default = models.BooleanField(
        default=False,
        help_text=("Whether this host is used as the default value on the event form"),
    )
    external = models.BooleanField(
        default=False,
        help_text=_(
            "External hosts are for NPSI API imports. Checking this box will hide the host in the manual event form."
        ),
    )

    def __str__(self):
        return str(self.community)

    class Meta:
        verbose_name = "Host"
        verbose_name_plural = "Hosts"

    def save(self, *args, **kwargs):
        if self.is_default:
            # select all other is_default items
            qs = type(self).objects.filter(is_default=True)
            # except self (if self already exists)
            if self.pk:
                qs = qs.exclude(pk=self.pk)
            # and deactive them
            qs.update(is_default=False)

        super(EventHost, self).save(*args, **kwargs)


class EventCategory(models.Model):
    name = models.CharField(
        max_length=150,
        help_text=_("Name for the category"),
    )
    ticker = models.CharField(
        max_length=10,
        help_text=_("Ticker for the category"),
    )
    color = models.CharField(
        max_length=7,
        default="",
        blank=True,
        help_text=_("Color to be displayed on calendar"),
    )
    description = models.TextField(
        blank=True,
        help_text="Prefilled description that will be added on default on the event description.",
    )

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return str(self.name)

    @property
    def get_category_class(self):
        return f"{self.name.replace(' ', '-').lower()}"


class EventImport(models.Model):
    """NPSI IMPORT OPTIONS"""

    SPECTRE_FLEET = "SF"
    EVE_UNIVERSITY = "EU"
    FUN_INC = "FI"
    FRIDAY_YARRRR = "FY"
    REDEMPTION_ROAD = "RR"
    CAS = "CA"
    FWAMING_DWAGONS = "FD"
    FREE_RANGE_CHIKUNS = "FR"
    EVE_LINKNET = "LN"

    IMPORT_SOURCES = [
        (EVE_LINKNET, _("EVE LinkNet")),
        (SPECTRE_FLEET, _("Spectre Fleet")),
        (EVE_UNIVERSITY, _("EVE University")),
        (FUN_INC, _("Fun Inc.")),
        (FRIDAY_YARRRR, _("FRIDAY YARRRR")),
        (REDEMPTION_ROAD, _("Redemption Road")),
        (CAS, _("CAS")),
        (FWAMING_DWAGONS, _("Fwaming Dwagons")),
        (FREE_RANGE_CHIKUNS, _("FREE RANGE CHIKUNS")),
    ]

    source = models.CharField(
        max_length=32,
        choices=IMPORT_SOURCES,
        help_text="The API source where you want to pull events from",
    )

    host = models.ForeignKey(
        EventHost,
        on_delete=models.CASCADE,
        default=1,
        help_text="The AA host that will be used for the pulled events",
    )
    operation_type = models.ForeignKey(
        EventCategory,
        on_delete=models.CASCADE,
        help_text="Operation type and ticker that will be assigned for the pulled fleets",
    )
    creator = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        default="1",
        help_text="User that has been used to create the fleet (most often the superuser who manages the plugin)",
    )
    eve_character = models.ForeignKey(
        EveCharacter,
        null=True,
        on_delete=models.SET_NULL,
        help_text="Event creator main character",
    )
    event_visibility = models.ForeignKey(
        EventVisibility,
        on_delete=models.CASCADE,
        null=True,
        help_text=_("Visibility filter that dictates who is able to see this event"),
    )

    def __str__(self):
        return str(self.source)

opcalendar/templates/opcalendar/add_member.html
{% extends 'opcalendar/base.html' %}

{% block title %}
Add EventMember
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'opcalendar:calendar' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

opcalendar/templates/opcalendar/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% load static %}

{% block extra_css %}
    {% include 'bundles/jquery-datetimepicker-css.html' %}
    {% if NIGHT_MODE %}
    <link rel="stylesheet" type="text/css" href="{% static 'opcalendar/style_dark.css' %}">
    {% else %}
    <link rel="stylesheet" type="text/css" href="{% static 'opcalendar/style_light.css' %}">
    {% endif %}
{% endblock extra_css %}
{% block page_title %}{% trans title %}{% endblock %}

{% block content %}
    <h2 class="text-center">{{ title }}</h2>
    <div class="col-lg-14 container">
        {% block details %}{% endblock %}
    </div>
{% endblock %}
{% block extra_script %}

    $('#id_start_time').datetimepicker({
    setlocale: '{{ LANGUAGE_CODE }}',
    {% if NIGHT_MODE %}
        theme: 'dark',
    {% else %}
        theme: 'default',
    {% endif %}
    mask: true,
    format: 'Y-m-d H:i',
    minDate: 0
    });

    $('#id_end_time').datetimepicker({
    setlocale: '{{ LANGUAGE_CODE }}',
    {% if NIGHT_MODE %}
        theme: 'dark',
    {% else %}
        theme: 'default',
    {% endif %}
    mask: true,
    format: 'Y-m-d H:i',
    minDate: 0
    });

{% endblock extra_script %}

opcalendar/templates/opcalendar/calendar.html
{% extends 'opcalendar/base.html' %}
{% load bootstrap %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load evelinks %}
{% block page_title %}{% trans "Create Operation" %}{% endblock page_title %}

{% block content %}
<div class="allianceauth-opcalendar">
    <div class="clearfix">
    	<a class="btn btn-info right mr-2" href="{% url 'opcalendar:calendar' %}?{{ next_month }} "> Next Month <i class="fas fa-forward"></i></a>
        <a class="btn btn-info right mr-2" href="{% url 'opcalendar:calendar' %}?{{ prev_month }}"><i class="fas fa-backward"></i> Previous Month </a>
            {% if perms.opcalendar.create_event %}
        	<a class="btn btn-info right mr-2" href="{% url 'opcalendar:event_new' %}"><i class="fas fa-calendar-plus"></i> New Event </a>
        {% endif %}
        {% if perms.opcalendar.add_ingame_calendar_owner %}
            <a class="btn btn-success right mr-2" href="{% url 'opcalendar:add_ingame_calendar' %}"><i class="fas fa-sync"></i>
            {% translate "Add Ingame Calendar Feed" %}
            </a>
        {% endif %}
        <h5>Legend & Filters:</h5>
        <div class="legend">
            <div>
                <span class="event show-all">Show all</span>
                <span class="event ingame-event">Ingame</span>
                {% for event in visibility %}
                     <style>.{{ event.get_visibility_class }}:before {border-color: transparent {{ event.color }} transparent transparent;border-style: solid;}</style>
                     <span class="event {{ event.get_visibility_class }}">{{ event.name }}</span>
                {% endfor %}
        	</div>
        	<div>
        		{% if moonmining_active %}
                    <span class="event event-moonmining">Moon Mining</span>
                {% endif %}
                {% if structuretimers_active %}
                    <span class="event event-structuretimer">Timers</span>
                {% endif %}
                {% for event in category %}
        			<span class="event {{ event.get_category_class }}">{{ event.name }}</span>
        		{% endfor %}
        	</div>
        </div>
    </div>
</div>
<div>
    <div class="allianceauth-opcalendar">
        {{ calendar }}
    </div>
</div>
{% endblock content %}

{% block extra_javascript %}
    {% include 'bundles/jquery-datetimepicker-js.html' %}
    <script>
        let selectedEvents = []

        $('.legend').on('click', 'span', function(){
            const classes = $(this).attr('class')
            const selectors = '.' + classes.split(' ').join('.').replace('.active', '')

            // clear all selections on show-all
            if(selectors.includes('show-all')){
                selectedEvents = []
                $('.legend .event').removeClass('active')
                $(this).addClass('active')
            }

            // remove current selection if it's already present in the selectedEvents array
            else if(selectedEvents.includes(selectors)){
                selectedEvents = selectedEvents.filter(event => event !== selectors)
                $(this).removeClass('active')
            }

            // add the current selection to the selectedEvents array
            else{
                selectedEvents.push(selectors)
                $(this).addClass('active')
            }

            applyCalendarFilters(selectedEvents)

        })

        function applyCalendarFilters(selectedEvents){
            $('.calendar .event').hide()

            if(selectedEvents.length){
                selectedEvents.forEach(selectors => $('.calendar ' + selectors).show())
            }
            else{
                $('.calendar .event').show()
            }
        }
    </script>
{% endblock %}

opcalendar/templates/opcalendar/event-add.html
{% extends 'opcalendar/base.html' %}
{% load bootstrap %}
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block page_title %}{% trans "Create Operation" %}{% endblock page_title %}
{% block extra_css %}
    {% include 'bundles/jquery-datetimepicker-css.html' %}
{% endblock extra_css %}

{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header text-center">{% trans "Create New Event" %}</h1>

        <div class="container-fluid">
            <div class="col-md-4 col-md-offset-4">
                <div class="row">
                    <div class="allianceauth-opcalendar">
                        <form class="form-signin" role="form" action="" method="POST">
                            {% csrf_token %}
                            {{ form|bootstrap }}
                            <br/>
                            <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Create New Event" %}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block extra_javascript %}
  <script>
    $("#id_operation_type").change(function () {
      var id = $(this).val();
      $.ajax({
        url: 'ajax/get_category/',
        data: {
          'category': id
        },
        dataType: 'json',
        success: function (data) {
            var events = JSON.parse(data.category);
            var obj = events[0];
            var fields = obj.fields;
          console.log( fields.description );
          $('#id_description').val(fields.description);
        }
      });

    });
  </script>


    {% include 'bundles/jquery-datetimepicker-js.html' %}
{% endblock %}

opcalendar/templates/opcalendar/event-details.html
{% extends 'opcalendar/base.html' %}
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block title %}
Event Details
{% endblock %}

{% block content %}
    <div class="container">
        <div class="allianceauth-opcalendar">
            <div class="clearfix">
                <a class="btn btn-primary left" href="{% url 'opcalendar:calendar' %}"><i class="far fa-calendar-alt"></i> Calendar </a>
                <a class="btn btn-success left" href="{% url 'opcalendar:event-ical-view' event.pk %}"><i class="fas fa-bookmark"></i> Add to my calendar </a>
                {% if perms.opcalendar.create_event %}
                    {% if not event.external %}
                        <a class="btn btn-primary left mr-2" href="{% url 'opcalendar:event_edit' event.pk %}"><i class="fas fa-edit"></i> Edit Event </a>
                        <a class="btn btn-danger" href="{% url 'opcalendar:remove_event' event.id %}"><i class="fas fa-trash"></i> Remove</a>
                    {% endif %}
                {% endif %}
            </div>

            <div class="clearfix">
                <div class="col-lg-12 text-center row">
                <div class="label label-info text-left">
                    <b>{% trans "Current Eve Time:" %} </b>
                </div>
                <strong class="label label-info text-left" id="current-time"></strong>
                <br  />
            </div>
                <h2>{{ event.title }}</h2>
                <p>Created by: <span style="color: gray;">{{ event.eve_character }}</span> Starts in: <span id="countdown{{ event.id }}" style="color: gray;">{{ event.eve_character }}</span></p>
                <hr>
                <h4>Event details</h4>
                <style>.{{event.get_visibility_class}}:before{border-color: transparent {{event.event_visibility.color}} transparent transparent;border-style: solid;} .{{event.get_category_class}} {border-left: 6px solid {{event.operation_type.color}} !important;}
                </style>
                <table>
                    <tr>
                        <td style="padding-right: 10px;"><b>Type:</b></td>
                        <td><span class="event {{ event.get_category_class }}">{{ event.operation_type }}</span></td>
                    </tr>
                    <tr>
                        <td style="padding-right: 10px;"><b>Availability:</b></td>
                        <td><span class="event {{ event.get_visibility_class }}">{{ event.event_visibility }}</span></td>
                    </tr>
                    <tr>
                        <td style="padding-right: 10px;"><b>Start time:</b></td>
                        <td>{{ event.start_time|date:"D Y-m-d H:i" }} (EVE) / <span id="localtime{{ event.id }}"></span> (Local)</td>
                    </tr>

                    <tr>
                        <td style="padding-right: 10px;"><b>Est. end time:</b></td>
                        <td>{{ event.end_time|date:"D Y-m-d H:i" }}</td>
                    </tr>
                    <tr>
                        <td style="padding-right: 10px;"><b>Duration:</b></td>
                        <td>{{ event.duration }}</td>
                    </tr>
                    <tr>
                        <td style="padding-right: 10px;"><b>Formup location:</b></td>
                        <td>{{ event.formup_system }}</td>
                    </tr>
                    <tr>
                        <td style="padding-right: 10px;"><b>Doctrine:</b></td>
                        <td>{{ event.doctrine }}</td>
                    </tr>
                    <tr>
                        <td style="padding-right: 10px;"><b>Fleet Commander:</b></td>
                        <td>{{ event.fc }}</td>
                    </tr>
                </table>
                <p style="padding-top:40px">{{ event.description|striptags|urlize|linebreaks}}</p>
                <hr>
                <h4>Host details</h4>
                <table>
                    <tr>
                        <td style="padding-right: 10px;"><b>Community:</b></td>
                        <td><span>{{ event.host.community|urlize }}</span></td>
                    </tr>
                    <tr>
                        <td style="padding-right: 10px;"><b>Ingame channel:</b></td>
                        <td><span>{{ event.host.ingame_channel|urlize }}</span></td>
                    </tr>
                    <tr>
                        <td style="padding-right: 10px;"><b>Ingame mailing list:</b></td>
                        <td><span>{{ event.host.ingame_mailing_list|urlize }}</span></td>
                    </tr>
                    <tr>
                        <td style="padding-right: 10px;"><b>Fleet comms:</b></td>
                        <td><span>{{ event.host.fleet_comms|urlize }}</span></td>
                    </tr>
                    <tr>
                        <td style="padding-right: 10px;"><b>Fleet doctrines:</b></td>
                        <td><span>{{ event.host.fleet_doctrines|urlize }}</span></td>
                    </tr>
                    <tr>
                        <td style="padding-right: 10px;"><b>Website:</b></td>
                        <td><span>{{ event.host.website|urlize }}</span></td>
                    </tr>
                    <tr>
                        <td style="padding-right: 10px;"><b>Discord:</b></td>
                        <td><span>{{ event.host.discord|urlize }}</span></td>
                    </tr>
                    <tr>
                        <td style="padding-right: 10px;"><b>Twitch:</b></td>
                        <td><span>{{ event.host.twitch|urlize }}</span></td>
                    </tr>
                    <tr>
                        <td style="padding-right: 10px;"><b>Twitter:</b></td>
                        <td><span>{{ event.host.twitter|urlize }}</span></td>
                    </tr>
                    <tr>
                        <td style="padding-right: 10px;"><b>Youtube:</b></td>
                        <td><span>{{ event.host.youtube|urlize }}</span></td>
                    </tr>
                    <tr>
                        <td style="padding-right: 10px;"><b>Facebook:</b></td>
                        <td><span>{{ event.host.facebook|urlize }}</span></td>
                    </tr>
                </table>
                <p style="padding-top:40px">{{ event.host.details }}</p>
            </div>
        </div>
            <div>
                <div>
                    {% if not request.user.profile.main_character.character_name in memberlist %}
                        <a class="btn btn-success right" href="{% url 'opcalendar:event_member_signup' event.id %}">Sign me up for the event</a>
                    {% else %}
                        <a class="btn btn-danger" href="{% url 'opcalendar:event_member_remove' event.id %}">Remove my event signup</a>
                    {% endif %}
                </div>

                {% if perms.opcalendar.see_signups %}
                    <table class="table table-bordered">
                    <thead>
                        <tr>
                          <th style="width: 10px">#</th>
                          <th>Main Character</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for member in eventmember %}
                        <tr role="row">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ member.character }}</td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                {% endif %}
        </div>
    </div>
    </div>
{% include 'bundles/moment-js.html' with locale=True %}
    <script src="{% static 'js/timers.js' %}"></script>
    <script type="application/javascript">
        // Data
        var timers = [
            {
                'id': {{ event.id }},
                'start': moment("{{ event.start_time | date:"c" }}"),
                'expired': false
            },
        ];
    </script>
    <script type="application/javascript">

        timedUpdate();
        setAllLocalTimes();

        // Start timed updates
        setInterval(timedUpdate, 1000);

        function timedUpdate() {
            updateClock();
            updateAllTimers();
        }

        function updateAllTimers () {
            var l = timers.length;
            for (var i=0; i < l; ++i) {
                if (timers[i].expired) continue;
                updateTimer(timers[i]);
            }
        }

        /**
         * Update a timer
         * @param timer Timer information
         * @param timer.start Date of the timer
         * @param timer.id Id number of the timer
         * @param timer.expired
         */
        function updateTimer(timer) {
            if (timer.start.isAfter(Date.now())) {
                var duration = moment.duration(timer.start - moment(), 'milliseconds');
                document.getElementById("countdown" + timer.id).innerHTML = getDurationString(duration);
            } else {
                timer.expired = true;
                document.getElementById("countdown" + timer.id).innerHTML = "";
            }
        }

        /**
         * Set all local time fields
         */
        function setAllLocalTimes() {
            var l = timers.length;
            for (var i=0; i < l; ++i) {
                setLocalTime(timers[i]);
            }
        }

        /**
         * Set the local time info for the timer
         * @param timer Timer information
         * @param timer.start Date of the timer
         * @param timer.id Id number of the timer
         */
        function setLocalTime(timer) {
            document.getElementById("localtime" + timer.id).innerHTML = timer.start.format("ddd MM-DD HH:mm");
        }

        function updateClock() {
            document.getElementById("current-time").innerHTML = getCurrentEveTimeString();
        }
    </script>
{% endblock %}

opcalendar/templates/opcalendar/event-edit.html
{% extends 'opcalendar/base.html' %}
{% load bootstrap %}
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block page_title %}{% trans "Create Operation" %}{% endblock page_title %}
{% block extra_css %}
    {% include 'bundles/jquery-datetimepicker-css.html' %}
{% endblock extra_css %}

{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header text-center">{% trans "Edit Event" %}</h1>
        <div class="container-fluid">
            <div class="col-md-4 col-md-offset-4">
                <div class="row">
                    <div class="allianceauth-opcalendar">
                        <form class="form-signin" role="form" action="" method="POST">
                            {% csrf_token %}
                            {{ form|bootstrap }}
                            <br/>
                            <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Edit Event" %}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block extra_javascript %}
    {% include 'bundles/jquery-datetimepicker-js.html' %}
{% endblock %}

opcalendar/templates/opcalendar/event_delete.html
<!-- templates/article_delete.html -->
{% extends 'opcalendar/base.html' %}

{% block title %}
Event Delete
{% endblock %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete this event?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}

opcalendar/templates/opcalendar/signup.html
{% extends 'opcalendar/base.html' %}

{% block title %} Signup {% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6  m-2">
        <form action="" method="post">
            {% csrf_token %}
            {{ form }}
            <input class="btn btn-primary mt-2" type="submit" value="Signup">
        </form>
    </div>
</div>
{% endblock %}